[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-db-entities"
version = "0.6.4"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
poem-openapi = { version = "^2.0.10", features = ["chrono", "uuid"] }
sea-orm = { version = "^0.10", features = [
    "macros",
    "with-chrono",
    "with-uuid",
    "with-json",
], default-features = false }
serde = "1.0"
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
warpgate-common = { version = "*", path = "../warpgate-common" }
