[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-admin"
version = "0.4.0"

[dependencies]
anyhow = { version = "1.0", features = ["std"] }
async-trait = "0.1"
bytes = "1.2"
chrono = "0.4"
futures = "0.3"
hex = "0.4"
mime_guess = { version = "2.0", default_features = false }
poem = { version = "^1.3.36", features = [
    "cookie",
    "session",
    "anyhow",
    "websocket",
] }
poem-openapi = { version = "^2.0.4", features = [
    "swagger-ui",
    "chrono",
    "uuid",
    "static-files",
] }
russh-keys = { version = "0.22.0-beta.6", features = ["openssl"] }
rust-embed = "6.3"
sea-orm = { version = "^0.9", features = [
    "sqlx-sqlite",
    "runtime-tokio-native-tls",
    "macros",
], default-features = false }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = {version = "1.20", features = ["tracing"]}
tracing = "0.1"
uuid = { version = "1.0", features = ["v4", "serde"] }
warpgate-common = { version = "*", path = "../warpgate-common" }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities" }
warpgate-protocol-ssh = { version = "*", path = "../warpgate-protocol-ssh" }
regex = "1.6"
