[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-protocol-http"
version = "0.4.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
cookie = "0.16"
data-encoding = "2.3"
delegate = "0.6"
futures = "0.3"
http = "0.2"
lazy_static = "1.4"
poem = {version = "^1.3.47", features = ["cookie", "session", "anyhow", "rustls", "websocket", "sse", "embed"]}
poem-openapi = {version = "^2.0.6", features = ["swagger-ui"]}
reqwest = {version = "0.11", features = ["rustls-tls-native-roots", "stream"]}
serde = "1.0"
serde_json = "1.0"
tokio = {version = "1.20", features = ["tracing", "signal"]}
tokio-tungstenite = {version = "0.17", features = ["rustls-tls-native-roots"]}
tracing = "0.1"
warpgate-admin = {version = "*", path = "../warpgate-admin"}
warpgate-common = {version = "*", path = "../warpgate-common"}
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
warpgate-web = {version = "*", path = "../warpgate-web"}
percent-encoding = "2.1"
uuid = {version = "1.0", features = ["v4"]}
regex = "1.6"
