[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-db-migrations"
publish = false
version = "0.4.0"

[lib]

[dependencies]
async-std = "^1.11"
chrono = "0.4"
sea-orm = {version = "^0.10", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros", "with-chrono", "with-uuid", "with-json"], default-features = false}
sea-orm-migration = {version = "^0.9", default-features = false}
uuid = {version = "1.0", features = ["v4", "serde"]}
