[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-db-migrations"
publish = false
version = "0.6.4"

[lib]

[dependencies]
async-std = { version = "^1.12", features = ["attributes"] }
chrono = "0.4"
sea-orm = { version = "0.10.2", features = [
    "runtime-tokio-native-tls",
    "macros",
    "with-chrono",
    "with-uuid",
    "with-json",
], default-features = false }
sea-orm-migration = { version = "0.10.2", default-features = false, features = [
    "cli",
] }
uuid = { version = "1.0", features = ["v4", "serde"] }
serde_json = "1.0"
